name: 'Branch Restriction'

on:
  pull_request:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  check-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check Branch and fail
        run: |
          if [ "${{ github.event.pull_request.base.ref }}" != "main" ] || [ "${{ github.event.pull_request.head.ref }}" != "develop" ]; then
            echo "Only pull requests from 'develop' to 'main' are allowed."
            exit 1
          fi
