name: 'Pull Request Labeler'

on:
  pull_request:
    branches: [main]

jobs:
  labeler:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: labeling
        uses: actions/labeler@v5
        with:
          configuration-path: .github/configs/labeler.yml
